export const ENDPOINTS = {
  auth: {
    login: 'login/',
    register: 'registro/',
    registerClient: 'registrar/',
    logout: 'logout/',
    passwordResetRequest: 'password-reset-request/',
    passwordResetConfirm: 'password-reset-confirm/',
    refresh: 'token/refresh/',
    profile: 'perfil/',
  },
  admin: 'administrador/',
  agentes: 'agentes/',
  clientes: 'clientes/',
  bitacoras: 'bitacoras/',
  roles: 'roles/',
  permisos: 'permisos/',
  tipoSeguros: 'tipo-seguros/',
  planes: 'planes/',
  clausulas: 'clausulas/',
  cotizaciones: 'cotizaciones/',
  polizas: 'polizas/',
  renovaciones: 'renovaciones/',
  expedientes: 'expedientes/',
  ordenesMedicas: 'ordenes-medicas/',
};
